# Generated by Django 4.2.8 on 2023-12-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0002_alter_avaliacao_options_alter_curso_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="media_avaliacoes",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
